name: Terraform Validate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment (dev / uat / prod)"
        required: true
        default: "dev"

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init -backend-config=enviornments/${{ github.event.inputs.environment }}/backend.tfvars
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate
