name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment (dev / uat / prod)"
        required: true
        default: "dev"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -input=false -backend-config=enviornments/${{ github.event.inputs.environment }}/backend.tfvars

      - name: Terraform Plan
        run: terraform plan -var-file=enviornments/${{ github.event.inputs.environment }}/${{ github.event.inputs.environment }}.tfvars -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
